"""Rename username column

Revision ID: 3996afafbfb
Revises: 405fb9511e
Create Date: 2015-01-29 23:11:46.613926

"""

# revision identifiers, used by Alembic.
revision = '3996afafbfb'
down_revision = '405fb9511e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user', new_column_name='username', existing_type=sa.String(length=100), existing_server_default=False, existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', new_column_name='user', existing_type=sa.String(length=100), existing_server_default=False, existing_nullable=True)
    ### end Alembic commands ###
