"""Increase password length

Revision ID: 405fb9511e
Revises: 851852b6a0
Create Date: 2015-01-29 22:46:58.408615

"""

# revision identifiers, used by Alembic.
revision = '405fb9511e'
down_revision = '851852b6a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    ### end Alembic commands ###
