"""Add GPlus ID

Revision ID: 7a6e73773b
Revises: 3996afafbfb
Create Date: 2015-02-26 14:11:38.051433

"""

# revision identifiers, used by Alembic.
revision = '7a6e73773b'
down_revision = '3996afafbfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gplus_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'users', ['gplus_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'gplus_id')
    ### end Alembic commands ###
